name: kaldi-sale-checker

on:
  schedule:
    - cron: '*/30 * * * *'   # UTC で毎 30 分
  workflow_dispatch:          # 手動トリガーも可能

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python scraper.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
